import type { MenuItem } from './types';

// Sin id — PostgreSQL lo asigna automáticamente via SERIAL
type SeedItem = Omit<MenuItem, 'id'>;

let n = 0;
const r = (
  categoria: string, subcategoria: string, nombre: string,
  descripcion: string, precio: number, precio_alternativo = ''
): SeedItem => ({
  categoria, subcategoria, nombre, descripcion,
  precio, precio_alternativo, imagen_url: '', activo: true, orden: ++n,
});

export const SEED_ITEMS: SeedItem[] = [
  // ── BRUNCH ──────────────────────────────────────────────────────────────
  r('BRUNCH', 'DE CAMPO',      'Tostón de Campo',   'Tostón con palta y huevo + fetas de jamón y queso', 11400, 'Para compartir: $20.000'),
  r('BRUNCH', 'ITALIAN CUBIC', 'Focaccia Rellena',  'Focaccia rellena de jamón y queso',                 10500, 'Para compartir: $17.000'),
  r('BRUNCH', 'PARISINO',      'Croissant Relleno', 'Dulce o salado (consultar variedades)',              8000,  'Para compartir: $16.000'),
  r('BRUNCH', 'FITNESS',       'Yogurt con Frutas', 'Yogurt con frutas frescas + mix frutos secos + 2 tostadas integrales + jugo chico + dip queso y dulce', 13000, 'Para compartir: $23.000'),

  // ── PROMOS ───────────────────────────────────────────────────────────────
  r('PROMOS', 'PROMO 1', 'Infusión + Torta o Medialuna', 'Infusión grande + torta o medialuna',                                                  3000,  'Para compartir: $5.500'),
  r('PROMOS', 'PROMO 2', 'Infusión + Tostadas',          'Infusión grande + 2 tostadas + queso crema y dulce + jugo chico',                      5000,  'Para compartir: $9.500'),
  r('PROMOS', 'PROMO 3', 'Infusión + Tostado/Panini',    'Infusión grande + jugo chico + tostado o panini o sandwich frío con tomate y lechuga', 7800,  'Para compartir: $12.600'),
  r('PROMOS', 'PROMO 4', 'Infusión + Torta + Jugo',      'Infusión grande + porción de torta + jugo chico',                                      10000, 'Para compartir: $18.000'),

  // ── CAFETERIA E INFUSIONES ───────────────────────────────────────────────
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Café Solo',        '', 2500, 'Mediano: $2.800 / Grande: $3.300'),
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Cortado',          '', 2500, 'Mediano: $2.800 / Grande: $3.300'),
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Goteado',          '', 2500, 'Mediano: $2.800 / Grande: $3.300'),
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Manchado',         '', 2500, 'Mediano: $2.800 / Grande: $3.300'),
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Latte',            '', 2500, 'Mediano: $2.800 / Grande: $3.300'),
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Espresso Simple',  '', 2500),
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Espresso Doble',   '', 3300),
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Americano Simple', '', 2500),
  r('CAFETERIA E INFUSIONES', 'TRADICIONAL', 'Americano Doble',  '', 3300),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Flat White',       '', 4600),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Capuccino',        '', 6000),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Submarino',        '', 6000),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Chocolatada',      '', 4100),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Te Clásico',       '', 2100),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Te Saborizado',    '', 2900),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Ice Caramel',      '', 5000),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Ice Choco',        '', 5000),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Coffee Tonic',     '', 5000),
  r('CAFETERIA E INFUSIONES', 'ESPECIALES',  'Moka',             '', 5000),

  // ── PARA ACOMPAÑAR — DULCE ───────────────────────────────────────────────
  r('PARA ACOMPAÑAR', 'DULCE', 'Tortitas (Raspada/Hoja)',     '',                                 600),
  r('PARA ACOMPAÑAR', 'DULCE', 'Tortita c/ Jamón y Queso',   '',                                 1200),
  r('PARA ACOMPAÑAR', 'DULCE', 'Medialuna',                  '',                                 1000),
  r('PARA ACOMPAÑAR', 'DULCE', 'Medialuna c/ Jamón y Queso', '',                                 2000),
  r('PARA ACOMPAÑAR', 'DULCE', 'Croissant',                  '',                                 1500),
  r('PARA ACOMPAÑAR', 'DULCE', 'Croissant Relleno',          'Consultar opción dulce o salada',  4000),
  r('PARA ACOMPAÑAR', 'DULCE', 'Porción de Torta',           'Consultar variedades',             7500),
  r('PARA ACOMPAÑAR', 'DULCE', 'Mini Alfajor de Maizena',    '',                                 750),
  r('PARA ACOMPAÑAR', 'DULCE', 'Tostadas + Dip',             'Con queso o manteca y mermelada',  3900),
  r('PARA ACOMPAÑAR', 'DULCE', 'Porción Lemonie',            '',                                 2400),
  r('PARA ACOMPAÑAR', 'DULCE', 'Yogurth Natural c/ Frutas',  '',                                 9400),
  r('PARA ACOMPAÑAR', 'DULCE', 'Budín x 2 Porciones',        '',                                 3600),
  r('PARA ACOMPAÑAR', 'DULCE', 'Chipa x 2 Unidades',         '',                                 2200),

  // ── PARA ACOMPAÑAR — SALADO ──────────────────────────────────────────────
  r('PARA ACOMPAÑAR', 'SALADO', 'Panini Jamón & Queso',               '', 4500),
  r('PARA ACOMPAÑAR', 'SALADO', 'Panini Salame & Queso',              '', 4500),
  r('PARA ACOMPAÑAR', 'SALADO', 'Panini Mortadela & Queso',           '', 4500),
  r('PARA ACOMPAÑAR', 'SALADO', 'Panini Cheddar y Jamón',             '', 4500),
  r('PARA ACOMPAÑAR', 'SALADO', 'Panini Capresse',                    '', 4500),
  r('PARA ACOMPAÑAR', 'SALADO', 'Panini Jamón Crudo, Queso y Rúcula', '', 6000),
  r('PARA ACOMPAÑAR', 'SALADO', 'Tostado Chico',                      '', 4800),
  r('PARA ACOMPAÑAR', 'SALADO', 'Tostado Grande',                     '', 8000),
  r('PARA ACOMPAÑAR', 'SALADO', 'Sandwich Clásico', 'Con jamón, queso, lechuga y tomate', 5300),
  r('PARA ACOMPAÑAR', 'SALADO', 'Tostón de Campo',  'Con palta, huevo, jamón y queso',   8000),
  r('PARA ACOMPAÑAR', 'SALADO', 'Focaccia Rellena', 'Consultar variedades',              8500),
  r('PARA ACOMPAÑAR', 'SALADO', 'Huevos Revueltos', 'Con jamón y queso',                5700),

  // ── PARA ACOMPAÑAR — ADICIONALES ────────────────────────────────────────
  r('PARA ACOMPAÑAR', 'ADICIONALES', 'Dip de Palta',                     '',                  2200),
  r('PARA ACOMPAÑAR', 'ADICIONALES', 'Dip de Granola y Mix Frutos Secos', '',                 5100),
  r('PARA ACOMPAÑAR', 'ADICIONALES', 'Dip de Queso y Mermelada',          '',                 2000),
  r('PARA ACOMPAÑAR', 'ADICIONALES', 'Tostada Pan Blanco',                '',                 900),
  r('PARA ACOMPAÑAR', 'ADICIONALES', 'Tostada Pan Integral',              '',                 1150),
  r('PARA ACOMPAÑAR', 'ADICIONALES', 'Dip de Aceitunas',  'Verdes o negras', 1200),
  r('PARA ACOMPAÑAR', 'ADICIONALES', 'Maní o Papa Snack', '',                1200),

  // ── GLUTEN FREE ──────────────────────────────────────────────────────────
  r('GLUTEN FREE', '', 'Alfajores',                               'Consultar variedad',                 3800),
  r('GLUTEN FREE', '', 'Conito de Dulce de Leche',                '',                                   1800),
  r('GLUTEN FREE', '', 'Tostadas + Dip',                          'Con queso o manteca y mermelada',    4200),
  r('GLUTEN FREE', '', 'Baguetin con Jamón y Queso',              '',                                   4500),
  r('GLUTEN FREE', '', 'Baguetin con Jamón Crudo, Queso y Rúcula','',                                   6000),
  r('GLUTEN FREE', '', 'Ciabatta con Jamón y Queso',              '',                                   5500),
  r('GLUTEN FREE', '', 'Ciabatta con Jamón Crudo, Queso y Rúcula','',                                   7000),
  r('GLUTEN FREE', '', 'Sandwich Clásico', 'Con jamón, queso, lechuga y tomate',                        4800),
  r('GLUTEN FREE', '', 'Sandwich Pollo Teriyaki',                 '',                                   9800),
  r('GLUTEN FREE', '', 'Sandwich de Cerdo Braseado',              '',                                   9800),
  r('GLUTEN FREE', '', 'Lomo Completo', 'Pan casero o focaccia — lomo veteado, huevo, tomate, lechuga y lactonesa', 18000),
  r('GLUTEN FREE', '', 'Tostón de Campo', 'Con palta, huevo, jamón y queso',                            9000),
  r('GLUTEN FREE', '', 'Focaccia Rellena', 'Consultar variedades',                                      9500),
  r('GLUTEN FREE', 'PIZZAS GF', 'Muzzarella (4 porciones)',         '', 4500),
  r('GLUTEN FREE', 'PIZZAS GF', 'Especial (4 porciones)',           '', 5100),
  r('GLUTEN FREE', 'PIZZAS GF', 'Napolitana (4 porciones)',         '', 5100),
  r('GLUTEN FREE', 'PIZZAS GF', 'Fugazza (4 porciones)',            '', 5100),
  r('GLUTEN FREE', 'PIZZAS GF', 'Jamón Crudo y Rúcula (4 porciones)','', 6750),

  // ── PARA COMER ───────────────────────────────────────────────────────────
  r('PARA COMER', 'PICADAS',      'Picada Avenida',       '',            17700, '4 personas: $33.750'),
  r('PARA COMER', 'PICADAS',      'Picada Cubic',         '',            23250, '4 personas: $45.000'),
  r('PARA COMER', 'PAPAS FRITAS', 'Papas Tradicionales',  '',            4000,  'Grandes: $8.000'),
  r('PARA COMER', 'PAPAS FRITAS', 'Papas con Cheddar y Verdeo', '',      5500,  'Grandes: $9.500'),
  r('PARA COMER', 'PIZZAS',       'Muzarella',    '6 porciones',         6300,  '12 porciones: $11.700'),
  r('PARA COMER', 'PIZZAS',       'Especial',     '6 porciones',         6900,  '12 porciones: $12.600'),
  r('PARA COMER', 'PIZZAS',       'Napolitana',   '6 porciones',         6900,  '12 porciones: $12.600'),
  r('PARA COMER', 'PIZZAS',       'Fuggazetta',   '6 porciones',         6900,  '12 porciones: $12.600'),
  r('PARA COMER', 'PIZZAS',       'Hawaiana (Ananá)', '6 porciones',    9900,  '12 porciones: $18.000'),
  r('PARA COMER', 'PIZZAS',       'Jamón Crudo y Rúcula', '6 porciones', 9900, '12 porciones: $18.000'),
  r('PARA COMER', 'EMPANADAS',    'Carne o Pollo x 2',       '', 2500),
  r('PARA COMER', 'EMPANADAS',    'Jamón y Queso x 2',       '', 2000),
  r('PARA COMER', 'EMPANADAS',    'Capresse x 2',            '', 2000),
  r('PARA COMER', 'EMPANADAS',    'Cebolla y Muzzarella x 2','', 2000),
  r('PARA COMER', 'EMPANADAS',    'Atún x 2',                '', 2000),
  r('PARA COMER', 'EMPANADAS',    'Choclo x 2',              '', 2000),
  r('PARA COMER', 'ENSALADAS', 'Ensalada César',    'Colchón de verdes, cubos de pollo, crutones, escamas de queso y salsa César', 9800),
  r('PARA COMER', 'ENSALADAS', 'Ensalada Teriyaki', 'Colchón de verdes, láminas de pollo, tomates cherry confitados, cebolla morada, salsa teriyaki', 9800),
  r('PARA COMER', 'SANDWICH',  'Lomo Focaccia',          'Ternera, cerdo o pollo', 15000),
  r('PARA COMER', 'SANDWICH',  'Lomo Completo',           'Ternera, cerdo o pollo', 13000),
  r('PARA COMER', 'SANDWICH',  'Sandwich de Milanesa',    '', 13000),
  r('PARA COMER', 'SANDWICH',  'Sandwich Cerdo Braseado', '', 9800),
  r('PARA COMER', 'SANDWICH',  'Sandwich Pollo Teriyaki', '', 9800),
  r('PARA COMER', 'AL PLATO',  'Milanesa Napolitana', 'Con guarnición', 10000),
  r('PARA COMER', 'AL PLATO',  'Lomo o Suprema',      'Con guarnición', 10000),
  r('PARA COMER', 'AL PLATO',  'Cerdo Braseado',      'Con guarnición', 10000),
  r('PARA COMER', 'AL PLATO',  'Pollo Teriyaki',      'Con guarnición', 10000),
  r('PARA COMER', 'HAMBURGUESAS', 'Americana',           '', 0),
  r('PARA COMER', 'HAMBURGUESAS', 'Americana Doble',     '', 0),
  r('PARA COMER', 'HAMBURGUESAS', 'Bluecheese',          '', 0),
  r('PARA COMER', 'HAMBURGUESAS', 'Cheeseburger',        '', 0),
  r('PARA COMER', 'HAMBURGUESAS', 'Triple Cheeseburger', '', 0),
  r('PARA COMER', 'HAMBURGUESAS', 'Barba Burger',        '', 0),
  r('PARA COMER', 'HAMBURGUESAS', 'Classic Burger',      '', 0),

  // ── BEBIDAS SIN ALCOHOL ──────────────────────────────────────────────────
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Línea Pepsi — Lata/350cc/500cc',    '', 2200),
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Línea Pepsi — 1,5 lts',             '', 4420),
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Línea Coca Cola — Lata/350cc/500cc','', 2730),
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Línea Coca Cola — 1,5 lts',         '', 5460),
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Aguas Saborizadas 500cc',            '', 2200),
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Aguas Saborizadas 1,5 lts',          '', 4420),
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Agua Mineral Sin Gas 500cc',         '', 2200),
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Agua Mineral Con Gas 500cc',         '', 2340),
  r('BEBIDAS SIN ALCOHOL', 'GASEOSAS',     'Gatorade 500cc',                     '', 3120),
  r('BEBIDAS SIN ALCOHOL', 'ENERGIZANTES', 'Red Bull',                           '', 6000),
  r('BEBIDAS SIN ALCOHOL', 'ENERGIZANTES', 'Monster',                            '', 7500),
  r('BEBIDAS SIN ALCOHOL', 'JUGOS',        'Limonada/Pomelada Individual',       '', 3770, 'Jarra: $7.800'),
  r('BEBIDAS SIN ALCOHOL', 'JUGOS',        'Licuados', 'Consultar variedades',    3770),
  r('BEBIDAS SIN ALCOHOL', 'JUGOS',        'Naranja Individual',                 '', 3000, 'Jarra: $6.000'),

  // ── BEBIDAS CON ALCOHOL ──────────────────────────────────────────────────
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Quilmes Litro',                   '', 5500),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Andes Origen Litro',              '', 6500),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Stella Artois Litro',             '', 7800),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Patagonia 730cc',                 '', 8000),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Corona 710cc',                    '', 8000),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Michelob 473cc',                  '', 4350),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Corona 330cc',                    '', 5500),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Stella 330cc',                    '', 5500),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Corona 0.0 330cc',                '', 5200),
  r('BEBIDAS CON ALCOHOL', 'CERVEZA',   'Stella 0.0 330cc',                '', 5200),
  r('BEBIDAS CON ALCOHOL', 'VINOS',     'Nave Robino',                     '', 16000),
  r('BEBIDAS CON ALCOHOL', 'VINOS',     'Dante Robino',                    '', 13500),
  r('BEBIDAS CON ALCOHOL', 'VINOS',     'Novecento',                       '', 11000),
  r('BEBIDAS CON ALCOHOL', 'VINOS',     'Emilia',                          '', 6000),
  r('BEBIDAS CON ALCOHOL', 'VINOS',     'Otro Loco Ice',                   '', 6000),
  r('BEBIDAS CON ALCOHOL', 'CHAMPAGNE', 'Nave Robino',                     '', 16000),
  r('BEBIDAS CON ALCOHOL', 'CHAMPAGNE', 'Capricio Fiore',                  '', 13500),
  r('BEBIDAS CON ALCOHOL', 'CHAMPAGNE', 'Novecento',                       '', 12300),
  r('BEBIDAS CON ALCOHOL', 'CHAMPAGNE', 'Cinzano',                         '', 12300),
  r('BEBIDAS CON ALCOHOL', 'PROMOS',    'Jarra de Fernet',                 '', 17100),
  r('BEBIDAS CON ALCOHOL', 'PROMOS',    'Combo Champagne + 4 Red Bull',    '', 30000),
  r('BEBIDAS CON ALCOHOL', 'PROMOS',    'Combo Fernet + Coca Cola 1,25 lts','', 40000),
  r('BEBIDAS CON ALCOHOL', 'PROMOS',    'Combo Smirnoff + 4 Red Bull',     '', 40000),
];
